### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by coalkettler** [azavea/texturemap#4]
- [x] Create Netlify site for this repo
- [x] Configure `netlify.toml`
- [x] Configure Netlify DNS for texturemap.org

We should complete this prior to May 20, 2021, since Jeff is giving a presentation on it the following day.

**Comment by colekettler** [comment]
@jfrankl When would you like for this repo to go public so that the GitHub links on the site work?

**Comment by jfrankl** [comment]
@colekettler thank you for checking. I believe I made the repo public yesterday, but please let me know if I missed something there.

**Comment by colekettler** [comment]
@jfrankl Oh doy, I didn't even notice that. You've already got it covered!

**Comment by jfrankl** [comment]
I was really close to forgetting to make it public, so I'm glad you were thinking about it.
