### ISSUE TITLE
Not seeing patterns on texturemap.org

### ISSUE THREAD

**Issue by ddohler** [azavea/texturemap#6]
I'm not able to see the patterns on the project site in Firefox, Chrome, or Safari. This is what I see on the interactive demo, which looks different from what I saw during the presentation:
<img width="1436" alt="Screen Shot 2021-05-21 at 1 57 09 PM" src="https://user-images.githubusercontent.com/447977/119179071-7f364800-ba3c-11eb-8ce1-85451f945764.png">

I've confirmed that I can view patterns on the Mapbox documentation page for patterns, and I've also tested out the polygon demo and confirmed I can see the patterns there:
<img width="720" alt="Screen Shot 2021-05-21 at 1 59 06 PM" src="https://user-images.githubusercontent.com/447977/119179314-c45a7a00-ba3c-11eb-9bd2-12054a5276c1.png">
<img width="1440" alt="Screen Shot 2021-05-21 at 1 59 21 PM" src="https://user-images.githubusercontent.com/447977/119179326-c7ee0100-ba3c-11eb-94c4-e547f76e3efc.png">

**Comment by jfrankl** [comment]
@ddohler Thanks for taking a look at the project and for opening our first issue!

For some reason, I'm not able to recreate this issue in Firefox locally. Could you get me some additional information?

- OS version
- Firefox version
- Do you see any error in your console? Or in the network tab?
- Do you have an adblocker running? And does turning it off change anything?
- If you open it in an Incognito/Private window does this still happen?

**Comment by ddohler** [comment]
Just to be clear, this is happening on all browsers that I've tried so far, including Chrome, FF, and Safari.

Anyway, this is on me -- I should have checked the dev tools the first time around, there are plenty of errors! Here's a screenshot from Chrome:
<img width="1440" alt="Screen Shot 2021-05-24 at 8 20 02 AM" src="https://user-images.githubusercontent.com/447977/119347009-ef291600-bc68-11eb-964c-adb4b0991a5b.png">

I'm seeing the same thing in the Network tab as well -- there are 404 responses for files related to `polygons-sprite`:
<img width="1307" alt="Screen Shot 2021-05-24 at 8 21 37 AM" src="https://user-images.githubusercontent.com/447977/119347175-25ff2c00-bc69-11eb-9816-4471a490967b.png">

**Comment by jfrankl** [comment]
@ddohler thanks, that is super helpful. Could you take another look? I suspect it is fixed now.

**Comment by ddohler** [comment]
Indeed, everything is working as expected now! 🎉 
<img width="1431" alt="Screen Shot 2021-05-24 at 8 51 48 AM" src="https://user-images.githubusercontent.com/447977/119350422-4d57f800-bc6d-11eb-885f-362790858041.png">

**Comment by jfrankl** [comment]
Thank you for checking out the project and opening this issue. I'm really glad this bug got caught when it did.
